---
title: "Shiny Apps"
author: "Vineet Ahluwalia"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Shiny Apps}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The following vignette entails the working of the shiny apps included in the package:

* "draft" : This shiny app lets you explore the history of NBA drafts by colleges varying over years. For example: You can
select "Stanford" and see in a histogram formulation which teams drafted Stanford players. Also, you can download the histogram as a plot.

* "shotcharts" : This shiny app lets you plot and download shot chart of a player with varying attributes including
missed/not missed shot, in which quarter the shot was made etc. For example: You can choose "Stephen Curry" with outcome as an attribute which would plot the shots made and missed by Stephen Curry over the past twenty games.

## Launching an app

Use launchApp() with the name of the App to start using the interface

```{r, eval = FALSE}
rNBA::launchApp("draft")
rNBA::launchApp("shotcharts")
```
